/* ***** BEGIN LICENSE BLOCK *****
 * Version: GPL 3.0
 *
 * The contents of this file are subject to the General Public License
 * 3.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * Author: Adrien Dorsaz
 * Website: https://adorsaz.ch
 * email: adrien@adorsaz.ch
 *
 *
 * ***** BEGIN LICENSE BLOCK *****/

#include "nsISupports.idl"

[scriptable, uuid(7451198f-a392-41d3-b255-d1fdca7533b2)]
interface mivExchangeLoginManager : nsISupports
{
    // Return password for a specific account
    AUTF8String getPassword(in AUTF8String login, in AUTF8String serverURL, in AUTF8String httpRealm);
    // Delete password from cache
    void deletePassword (in AUTF8String password, in AUTF8String login, in AUTF8String serverURL, in AUTF8String httpRealm);
    // Check if user canceled password request
    boolean isUserCancelled(in AUTF8String login, in AUTF8String serverURL, in AUTF8String httpRealm);
    // Reset user password request cancellation
    void resetUserCancellation(in AUTF8String login, in AUTF8String serverURL, in AUTF8String httpRealm);
};
